project_name: aaaaaaaaa
changelog:
  filters:
    exclude:
      - (?i)moises
builds:
- binary: moises
  id: moises
  env:
  - CGO_ENABLED=0
  main: ./main.go
  goos:
  - darwin
  - linux
  goarch:
  - amd64
- binary: foo
  id: foo
  env:
  - CGO_ENABLED=0
  main: ./foo/main.go
  goos:
  - darwin
  - linux
  - windows
  goarch:
  - amd64
  - 386
- binary: bar
  id: bar
  env:
  - CGO_ENABLED=0
  main: ./bar/main.go
  goos:
  - linux
  - windows
  goarch:
  - amd64
  - 386
- binary: foobar
  id: foobar
  env:
  - CGO_ENABLED=0
  main: ./foobar/main.go
  ignore:
  - goos: darwin
    goarch: amd64
  - goos: linux
    goarch: amd64
brews:
-
  tap:
    owner: caarlos0
    name: homebrew-tap
  folder: Formula
  caveats: "Test formula, dont use it. It doesnt do anything"
  test: |
    system "#{bin}/foo"
    system "#{bin}/moises"
nfpms:
-
  formats:
  - deb

release:
  github:
    owner: caarlos0
    name: test

archives:
-
  name_template: '{{ .ProjectName }}-{{ .Version }}-{{ .Env.GOVERSION }}-{{ .Os }}_{{ .Arch }}'
  replacements:
    darwin: macOS
    amd64: 64bits
    windows: Windaum
dockers:
- image_templates: ["caarlos0/moises:{{.Version}}"]
  dockerfile: Dockerfile.moises
- image_templates: ["caarlos0/foo:{{.Version}}"]
  dockerfile: Dockerfile.foo
- image_templates: ["caarlos0/bar:{{.Version}}"]
  dockerfile: Dockerfile.bar
