# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
builds:
- env:
  - CGO_ENABLED=0
  goos:
  - linux
  binary: foobar/test
changelog:
  skip: true
nfpms:
- id: packages
  formats: ['deb', 'rpm', 'apk']
# gitlab_urls:
#   api: https://localhost:443/foo/bar
#   download: https://localhost:443/downloads
# release:
#   gitlab:
#     owner: foo
#     name: bar
# announce:
#   twitter:
#     enabled: true
#     message_template: 'test tweet plz ignore!\n{{ .ProjectName }} {{ .Tag }} is out! Check it out at https://github.com/caarlos0/test/releases/tag/{{ .Tag }}'
# furies:
# - account: caarlos0

brews:
  - tap:
      owner: caarlos0
      name: homebrew-tap
    folder: Formula
scoop:
  bucket:
    owner: caarlos0
    name: scoop-bucket
snapcrafts:
  - name_template: '{{ .ProjectName }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    summary: asdasd
    description: asdadasd
    grade: stable
    confinement: classic

publishers:
  - name: fury.io
    ids:
    - packages
    cmd: ./scripts/fury-upload.sh {{ .ArtifactName }}
