# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
builds:
  - binary: moises
    id: moises
    env:
      - CGO_ENABLED=0
    main: ./main.go
    goos:
      - windows

chocolateys:
  - name: foo
    owners: carlos
    title: lalal
    authors: carlos
    api_key: fake
    copyright: mit
    license_url: https://foo.com/mit
    summary: aaaa
    description: aaaaaa
    project_url: https://foo.com
