# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
builds:
- env:
  - CGO_ENABLED=1
  binary: mybin
  env:
  - CGO_ENABLED=0
  main: ./main.go
  goos:
  - linux
  goarch:
  - amd64
  - arm64
snapshot:
  name_template: '{{ .Tag | incminor }}-net'
dockers:
- name_templates: ["caarlos0/gmarchtest:{{ .Version }}-amd64"]
  binaries: ["mybin"]
  dockerfile: Dockerfile.multiarch
  build_flag_templates: ["--build-arg=ARCH=amd64"]
- name_templates: ["caarlos0/gmarchtest:{{ .Version }}-arm64v8"]
  binaries: ["mybin"]
  goarch: arm64
  dockerfile: Dockerfile.multiarch
  build_flag_templates: ["--build-arg=ARCH=arm64v8"]
docker_manifests:
- name_template: caarlos0/gmarchtest:{{ .Version }}
  image_name_templates:
  - caarlos0/gmarchtest:{{ .Version }}-amd64
  - caarlos0/gmarchtest:{{ .Version }}-arm64v8
