# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
builds:
- env:
  - CGO_ENABLED=0
  goos:
  - linux
changelog:
  skip: true
# gitlab_urls:
#   api: https://localhost:443/foo/bar
#   download: https://localhost:443/downloads
# release:
#   gitlab:
#     owner: foo
#     name: bar
