version: 2
# yaml-language-server: $schema=https://goreleaser.com/static/schema-pro.json
# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
builds:
  - binary: moises
    id: moises
    env:
      - CGO_ENABLED=0
    main: ./main.go
    goos:
      - windows
    goarch:
      - amd64

release:
  name_template: "v{{ .Version }}"
  mode: append
  # replace_existing_artifacts: true
  # skip_upload: true
  discussion_category_name: General
  footer: |
    ## Foo
    ### Bar
    - zaz
