# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
version: 2
builds:
  - env:
      - CGO_ENABLED=0
    binary: mybin
    main: ./main.go
    goos:
      - linux
    goarch:
      - amd64
      - arm64
dockers:
  - image_templates: ["caarlos0/gmarchtest:{{ .Version }}-amd64"]
    dockerfile: Dockerfile.multiarch
    build_flag_templates: ["--platform=linux/amd64"]
  - image_templates: ["caarlos0/gmarchtest:{{ .Version }}-arm64"]
    goarch: arm64
    dockerfile: Dockerfile.multiarch
    build_flag_templates: ["--platform=linux/arm64"]
docker_manifests:
  - name_template: caarlos0/gmarchtest:{{ .Version }}
    image_templates:
      - caarlos0/gmarchtest:{{ .Version }}-amd64
      - caarlos0/gmarchtest:{{ .Version }}-arm64
signs:
  - cmd: cosign
    env:
      - COSIGN_EXPERIMENTAL=1
    args:
      - "sign-blob"
      - "--rekor-url=https://rekor.sigstore.dev"
      - "--oidc-issuer=https://oauth2.sigstore.dev/auth"
      - "--output=${signature}"
      - "${artifact}"
    artifacts: all

docker_signs:
  - artifacts: all
    env:
      - COSIGN_EXPERIMENTAL=1
    args:
      - "sign"
      - "--rekor-url=https://rekor.sigstore.dev"
      - "--oidc-issuer=https://oauth2.sigstore.dev/auth"
      - "${artifact}"

release:
  skip: true
