# yaml-language-server: $schema=https://goreleaser.com/static/schema-pro.json
# vim: set ts=2 sw=2 tw=0 fo=jcroql

version: 2
project_name: foo

builds:
  - main: .
    binary: foo
    goos: [linux]
    goarch:
      - arm64
      - amd64

dockers:
  - goos: linux
    goarch: amd64
    image_templates:
      - "caarlos0/foo:{{.Tag}}-amd64"
    build_flag_templates:
      - --pull
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--build-arg=VERSION={{.Version}}"
      - "--build-arg=COMMIT_HASH={{.FullCommit}}"
      - "--build-arg=BUILD_DATE={{.Date}}"
    dockerfile: Dockerfile.foo

docker_manifests:
  - name_template: "caarlos0/foo:{{ .Version }}"
    create_flags:
      - "--annotation=com.gitlab.ci.user.name=test"
    image_templates:
      - "caarlos0/foo:{{ .Version }}-amd64"
