# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
builds:
- env:
  - CGO_ENABLED=0
  binary: mybin
  main: ./main.go
  goos:
  - linux
  goarch:
  - amd64
  - arm64
dockers:
- image_templates: ["caarlos0/gmarchtest:{{ .Version }}-amd64"]
  binaries: ["mybin"]
  use_buildx: true
  dockerfile: Dockerfile.multiarch
  build_flag_templates: ["--platform=linux/amd64"]
- image_templates: ["caarlos0/gmarchtest:{{ .Version }}-arm64"]
  binaries: ["mybin"]
  use_buildx: true
  goarch: arm64
  dockerfile: Dockerfile.multiarch
  build_flag_templates: ["--platform=linux/arm64"]
docker_manifests:
- name_template: caarlos0/gmarchtest:{{ .Version }}
  image_templates:
  - caarlos0/gmarchtest:{{ .Version }}-amd64
  - caarlos0/gmarchtest:{{ .Version }}-arm64
