# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
builds:
- env:
  - CGO_ENABLED=0
  goos:
  - linux
changelog:
  skip: true
nfpm:
- formats: ['deb', 'rpm', 'apk']
# gitlab_urls:
#   api: https://localhost:443/foo/bar
#   download: https://localhost:443/downloads
# release:
#   gitlab:
#     owner: foo
#     name: bar
# announce:
#   twitter:
#     enabled: true
#     message_template: 'test tweet plz ignore!\n{{ .ProjectName }} {{ .Tag }} is out! Check it out at https://github.com/caarlos0/test/releases/tag/{{ .Tag }}'
furies:
- account: caarlos0
