project_name: aaaaaaaaa
changelog:
  impl: github
  filters:
    exclude:
      - (?i)moises
builds:
- binary: moises
  id: moises
  env:
  - CGO_ENABLED=0
  main: ./main.go
  goos:
  - darwin
  - linux
  goarch:
  - amd64
- binary: foo
  id: foo
  env:
  - CGO_ENABLED=0
  main: ./foo/main.go
  goos:
  - darwin
  - linux
  goarch:
  - amd64
- binary: bar
  id: bar
  env:
  - CGO_ENABLED=0
  main: ./bar/main.go
  goos:
  - linux
  - darwin
  goarch:
  - amd64
brews:
-
  tap:
    owner: caarlos0
    name: homebrew-tap
    branch: feat-{{.Tag}}
    pull_request:
      enabled: true
  folder: Formula
  caveats: "Test formula, dont use it. It doesnt do anything"
  test: |
    system "#{bin}/foo"
    system "#{bin}/moises"
nfpms:
-
  formats:
  - deb

release:
  github:
    owner: caarlos0-graveyard
    name: test

# dockers:
# - image_templates: ["caarlos0/moises:{{.Version}}"]
#   dockerfile: Dockerfile.moises
# - image_templates: ["caarlos0/foo:{{.Version}}"]
#   dockerfile: Dockerfile.foo
# - image_templates: ["caarlos0/bar:{{.Version}}"]
#   dockerfile: Dockerfile.bar

# announce:
#   discord:
#    enabled: true
