# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
builds:
  - env:
      - CGO_ENABLED=0
    binary: mybin
    main: ./main.go
    goos:
      - linux
    goarch:
      - amd64
      - arm64

dockers_v2:
  - images:
      - "caarlos0/gmarchtest"
      - "ghcr.io/caarlos0/test"
    tags:
      - "v{{ .Version }}"
      - "{{ if .IsNightly }}nightly{{ end }}"
      - "{{ if not .IsNightly }}latest{{ end }}"
    extra_files:
      - scripts/entrypoint.sh
    platforms:
      - linux/amd64
      - linux/arm64
    labels:
      "org.opencontainers.image.description": "Release engineering, simplified"
      "org.opencontainers.image.created": "{{.Date}}"
      "org.opencontainers.image.name": "{{.ProjectName}}"
      "org.opencontainers.image.revision": "{{.FullCommit}}"
      "org.opencontainers.image.version": "{{.Version}}"
      "org.opencontainers.image.source": "{{.GitURL}}"

signs:
  - cmd: cosign
    env:
      - COSIGN_EXPERIMENTAL=1
    args:
      - "sign-blob"
      - "--rekor-url=https://rekor.sigstore.dev"
      - "--oidc-issuer=https://oauth2.sigstore.dev/auth"
      - "--output=${signature}"
      - "${artifact}"
    artifacts: all

docker_signs:
  - artifacts: all
    env:
      - COSIGN_EXPERIMENTAL=1
    args:
      - "sign"
      - "--rekor-url=https://rekor.sigstore.dev"
      - "--oidc-issuer=https://oauth2.sigstore.dev/auth"
      - "${artifact}"
