project_name: foo

dockers:
- goos: linux
  goarch: amd64
  image_templates:
  - "foo:true"
  dockerfile: true.Dockerfile

- goos: linux
  goarch: amd64
  image_templates:
  - "foo:false"
  dockerfile: false.Dockerfile
