includes:
  - from_url:
      url: charmbracelet/meta/bb22d197802c7b6586af5600a6dfaf3199b05eeb/goreleaser.yaml

project_name: foo

variables:
  description: "just me testing"
  github_url: "https://github.com/caarlos0/test"
  maintainer: "Carlos A Becker <carlos@beckeer.software>"
  homepage: "https://becker.software"
  docker_io_registry_owner: caarlos0
  ghcr_io_registry_owner: caarlos0-graveyard
  brew_owner: caarlos0
