project_name: test

builds:
- binary: test
  main: .
  goos:
    - linux
    - darwin
    - windows
  goarch:
    - amd64
    - arm64

universal_binaries:
  - replace: true

archives:
- format: binary

brews:
- tap:
    owner: caarlos0
    name: test
  folder: Formula
  caveats: "Test formula, dont use it. It doesnt do anything"

rigs:
- rig:
    owner: caarlos0
    name: test
