# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Test < Formula
  desc ""
  homepage ""
  version "1.1.10"
  depends_on :macos

  on_macos do
    url "https://github.com/caarlos0-graveyard/test/releases/download/v1.1.10/test_1.1.10_darwin_amd64.tar.gz"
    sha256 "f67ddb93eb882d147c98e4850bf99d4c624bc87d6d509e04968c5dc958ffd679"

    def install
      bin.install "moises"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Test
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end
end
