# This file was generated by GoReleaser. DO NOT EDIT.
cask "test" do
  desc ""
  homepage ""
  version "1.14.24"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "foo"

  on_macos do
    on_intel do
      url "https://github.com/caarlos0-graveyard/test/releases/download/v1.14.24/test_1.14.24_darwin_amd64.tar.gz"
      sha256 "4109dab578e1a53ac736c5f35408414012106c8f27010b86105daf3eb2615f5c"
    end
    on_arm do
      url "https://github.com/caarlos0-graveyard/test/releases/download/v1.14.24/test_1.14.24_darwin_arm64.tar.gz"
      sha256 "1bfc466747547ce2970b5ef055cb0cf2bfded1273b9f51051cb26672d4733e61"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/caarlos0-graveyard/test/releases/download/v1.14.24/test_1.14.24_linux_amd64.tar.gz"
      sha256 "28f3898a82a39d48421f9f60d8403c9199eea583a94bf6a00d55e2a1bb55a342"
    end
    on_arm do
      url "https://github.com/caarlos0-graveyard/test/releases/download/v1.14.24/test_1.14.24_linux_arm64.tar.gz"
      sha256 "05c7de22fe2b5f7c767b7e047dd7194a874d9c184104363e3de4313b13e0991e"
    end
  end

  conflicts_with formula: "test"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/foo"]
  end

  caveats do
    "Test formula, dont use it. It doesnt do anything"
  end

  # No zap stanza required
end
