# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Example < Formula
  desc ""
  homepage ""
  version "1.4.4"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/caarlos0-graveyard/test2/releases/download/example-v1.4.4/example-v1.4.4-darwin-arm64.tar.gz"
      sha256 "33ff43669a43f5b4fca587baaa24d269a24183950999f176760069a769a2ca73"

      def install
        bin.install "example"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/caarlos0-graveyard/test2/releases/download/example-v1.4.4/example-v1.4.4-darwin-amd64.tar.gz"
      sha256 "22525c59a7e90cb0cf5b9740d74a125d71539eaf8c5c58cc432cb373f203a8a3"

      def install
        bin.install "example"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/caarlos0-graveyard/test2/releases/download/example-v1.4.4/example-v1.4.4-linux-amd64.tar.gz"
      sha256 "a9e226d4729d0700626e913b68348a25b68c633e5053ae8e1ce864ffb772d5ba"

      def install
        bin.install "example"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/caarlos0-graveyard/test2/releases/download/example-v1.4.4/example-v1.4.4-linux-arm64.tar.gz"
      sha256 "e763e945a1e2f210144ea32aa6a2863c26c0a92affa80a845110fe0e948cecd1"

      def install
        bin.install "example"
      end
    end
  end

  def caveats
    <<~EOS
      Test formula, dont use it. It doesnt do anything
    EOS
  end
end
