# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Example < Formula
  desc ""
  homepage ""
  version "1.4.4"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/caarlos0-graveyard/test/releases/download/example-v1.4.4/example-v1.4.4-darwin-arm64.tar.gz"
      sha256 "f4599acb85c313f6aa07e4037d3377c7f98627e1a6371fd572616b829015acb9"

      def install
        bin.install "example"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/caarlos0-graveyard/test/releases/download/example-v1.4.4/example-v1.4.4-darwin-amd64.tar.gz"
      sha256 "9467381d22731ed223a4e6be040afaff91fe86c46c241c307e1c7cf6036bf3e9"

      def install
        bin.install "example"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/caarlos0-graveyard/test/releases/download/example-v1.4.4/example-v1.4.4-linux-arm64.tar.gz"
      sha256 "678250ca03fdd6a7b08db11c5bbb23d66b8d09b5808e0ad65565c50cac25f35d"

      def install
        bin.install "example"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/caarlos0-graveyard/test/releases/download/example-v1.4.4/example-v1.4.4-linux-amd64.tar.gz"
      sha256 "8ef985d7defbb99d000b1c3606a1641615e9b99d0b7a97ae99f5f8843ce72ee4"

      def install
        bin.install "example"
      end
    end
  end

  def caveats; <<~EOS
    Test formula, dont use it. It doesnt do anything
  EOS
  end
end
