# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Test < Formula
  desc ""
  homepage ""
  version "27.1.3"
  bottle :unneeded

  on_macos do
    url "https://github.com/caarlos0-graveyard/test/releases/download/v27.1.3/test_27.1.3_darwin_all"
    sha256 "e30cc4ae74061e44a6fae422766701fff74669c6e43ee127dfec326a966c00c0"

    def install
      bin.install "test_27.1.3_darwin_all" => "test"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/caarlos0-graveyard/test/releases/download/v27.1.3/test_27.1.3_linux_amd64"
      sha256 "1959178ca0836a5cdceec417675233f90862963b05708cb1f725c7b1fb46b400"

      def install
        bin.install "test_27.1.3_linux_amd64" => "test"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/caarlos0-graveyard/test/releases/download/v27.1.3/test_27.1.3_linux_arm64"
      sha256 "9a038a09cb2e2a3c40e1147898f3483703d5f4ca4086e724d23f627ecfd8fc11"

      def install
        bin.install "test_27.1.3_linux_arm64" => "test"
      end
    end
  end

  def caveats; <<~EOS
    Test formula, dont use it. It doesnt do anything
  EOS
  end
end
