# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TestATv1032 < Formula
  desc ""
  homepage ""
  version "1.0.32"

  on_macos do
    url "https://github.com/caarlos0-graveyard/test/releases/download/v1.0.32/test_1.0.32_darwin_amd64.tar.gz"
    sha256 "13b68d72b645101379df0c3673e0ae46c028891e9a4940cf68d392b869963068"

    def install
      bin.install "moises"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the TestATv1032
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/caarlos0-graveyard/test/releases/download/v1.0.32/test_1.0.32_linux_amd64.tar.gz"
      sha256 "0236ca4ad027c2ff35043b242a0c75e8c7339f5ec27e0df1b53967903c0e160d"

      def install
        bin.install "moises"
      end
    end
  end

  def caveats
    <<~EOS
      Test formula, dont use it. It doesnt do anything, versioned
    EOS
  end
end
