# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TestATv1033 < Formula
  desc ""
  homepage ""
  version "1.0.33"

  on_macos do
    url "https://github.com/caarlos0-graveyard/test/releases/download/v1.0.33/test_1.0.33_darwin_amd64.tar.gz"
    sha256 "4131af8e44bee76a74261ca4aca85752c0504102bddc0a5c59c9582d25b0558b"

    def install
      bin.install "moises"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the TestATv1033
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/caarlos0-graveyard/test/releases/download/v1.0.33/test_1.0.33_linux_amd64.tar.gz"
      sha256 "002742aced75d9fcccf8cafa943525f14dca6337f6fce7ee65af7aae1670aac0"

      def install
        bin.install "moises"
      end
    end
  end

  def caveats
    <<~EOS
      Test formula, dont use it. It doesnt do anything, versioned
    EOS
  end
end
