# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Test < Formula
  desc ""
  homepage ""
  version "24.3.1"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/caarlos0-graveyard/test/releases/download/v24.3.1/test_24.3.1_darwin_amd64.tar.gz"
      sha256 "cfa7b9c701fa1d4bfba326c356f2d1c69509f89411d542c16bd2f1c27f6761cb"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/caarlos0-graveyard/test/releases/download/v24.3.1/test_24.3.1_linux_amd64.tar.gz"
      sha256 "6f77c7e2b45f006ce6567b1d347a3632d46cc7ef46d19674cf740cac61e1a038"
    end
  end

  def install
    bin.install "test"
  end

  def caveats; <<~EOS
    Test formula, dont use it. It doesnt do anything
  EOS
  end
end
