name: release

on:
  push:
    tags:

jobs:
  goreleaser:
    uses: caarlos0/goreleaserfiles/.github/workflows/goreleaser.yml@main
    with:
      docker_username: caarlos0
    secrets:
      docker_password: ${{ secrets.DOCKER_PASSWORD }}
      gh_pat: ${{ secrets.GH_PAT }}
