name: release

on:
  push:
    tags: ['v*']

jobs:
  goreleaser:
    uses: charmbracelet/meta/.github/workflows/goreleaser.yml@main
    secrets:
      docker_username: caarlos0
      docker_token: ${{ secrets.DOCKER_PASSWORD }}
      gh_pat: ${{ secrets.GH_PAT }}
      goreleaser_key: ${{ secrets.GORELEASER_KEY }}
